# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   ORGANIZATIONS
#
#   This section defines the organizational identities that can be referenced
#   in the configuration profiles.
#
################################################################################
Organizations:

    - &OrdererOrg

        Name: OrdererOrg

        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/beacon.ph/msp

    - &beacon

        Name: beaconMSP

        ID: beaconMSP

        MSPDir: crypto-config/peerOrganizations/beacon.ph/msp

        AnchorPeers:
            - Host: peer0.beacon.ph
              Port: 7051

    - &auditor
        Name: auditorMSP

        ID: auditorMSP

        MSPDir: crypto-config/peerOrganizations/auditor.ph/msp

        AnchorPeers:
            - Host: peer0.auditor.ph
              Port: 7051

    - &co1
        Name: co1MSP

        ID: co1MSP

        MSPDir: crypto-config/peerOrganizations/co1.org/msp

        AnchorPeers:
            - Host: peer0.co1.org
              Port: 7051

    - &co2
        Name: co2MSP

        ID: co2MSP

        MSPDir: crypto-config/peerOrganizations/co2.org/msp

        AnchorPeers:
            - Host: peer0.co2.org
              Port: 7051

################################################################################
#
#   CAPABILITIES
#
#   This section defines the capabilities of fabric network. This is a new
#   concept as of v1.1.0 and should not be utilized in mixed networks with
#   v1.0.x peers and orderers.  Capabilities define features which must be
#   present in a fabric binary for that binary to safely participate in the
#   fabric network.  For instance, if a new MSP type is added, newer binaries
#   might recognize and validate the signatures from this type, while older
#   binaries without this support would be unable to validate those
#   transactions.  This could lead to different versions of the fabric binaries
#   having different world states.  Instead, defining a capability for a channel
#   informs those binaries without this capability that they must cease
#   processing transactions until they have been upgraded.  For v1.0.x if any
#   capabilities are defined (including a map with all capabilities turned off)
#   then the v1.0.x peer will deliberately crash.
#
################################################################################
Capabilities:

    Global: &ChannelCapabilities
        V1_1: true

    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_2: true

################################################################################
#
#   ORDERER
#
#   This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters.
#
################################################################################
Orderer: &OrdererDefaults

    OrdererType: solo

    Addresses:
        - orderer.beacon.ph:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

################################################################################
#
#   APPLICATION
#
#   This section defines the values to encode into a config transaction or
#   genesis block for application-related parameters.
#
################################################################################
Application: &ApplicationDefaults

    Organizations:

################################################################################
#
#   PROFILES
#
#   Different configuration profiles may be encoded here to be specified as
#   parameters to the configtxgen tool. The profiles which specify consortiums
#   are to be used for generating the orderer genesis block. With the correct
#   consortium members defined in the orderer genesis block, channel creation
#   requests may be generated with only the org member names and a consortium
#   name.
#
################################################################################
Profiles:

    OrdererGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            BeaconIdentities:
                Organizations:
                    - *beacon
                    - *auditor
                    - *co1
                    - *co2
            BeaconTransactionsCO1:
                Organizations:
                    - *beacon
                    - *auditor
                    - *co1
            BeaconTransactionsCO2:
                Organizations:
                    - *beacon
                    - *auditor
                    - *co2
            BeaconCampaigns:
                Organizations:
                    - *beacon
                    - *auditor
                    - *co1
                    - *co2

    identities:
        Consortium: BeaconIdentities
        Application:
            Organizations:
                - *beacon
                - *auditor
                - *co1
                - *co2
            Capabilities:
                <<: *ApplicationCapabilities

    transactionsco1:
        Consortium: BeaconTransactionsCO1
        Application:
            Organizations:
                - *beacon
                - *auditor
                - *co1
            Capabilities:
                <<: *ApplicationCapabilities

    transactionsco2:
        Consortium: BeaconTransactionsCO2
        Application:
            Organizations:
                - *beacon
                - *auditor
                - *co2
            Capabilities:
                <<: *ApplicationCapabilities

    campaigns:
        Consortium: BeaconCampaigns
        Application:
            Organizations:
                - *beacon
                - *auditor
                - *co1
                - *co2
            Capabilities:
                <<: *ApplicationCapabilities
