#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer
    Domain: beacon.ph
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: beacon
    Domain: beacon.ph
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: auditor
    Domain: auditor.ph
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: co1
    Domain: co1.org
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: co2
    Domain: co2.org
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1