# BEACON - Based on docker-compose-e2e-template.yaml
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.beacon.ph:
  ca.beacon.ph:
  ca.auditor.ph:
  ca.co1.org:
  ca.co2.org:
  peer0.beacon.ph:
  peer0.auditor.ph:
  peer1.auditor.ph:
  peer0.co1.org:
  peer1.co1.org:
  peer0.co2.org:
  peer1.co2.org:

networks:
  beacon:
services:
  ca.beacon.ph:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-beacon
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.beacon.ph-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8272d987c97be02461df4e1b131e52f4a0fa886d3bf306519f9eb0f3a39a4652_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.beacon.ph-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/8272d987c97be02461df4e1b131e52f4a0fa886d3bf306519f9eb0f3a39a4652_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/beacon.ph/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_beacon
    networks:
      - beacon

  ca.auditor.ph:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-auditor
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.auditor.ph-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/abfaf63d78d2a3bc5259b1b834e7f028b6ae94e967f7c50f399bf73b589c0882_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.auditor.ph-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/abfaf63d78d2a3bc5259b1b834e7f028b6ae94e967f7c50f399bf73b589c0882_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/auditor.ph/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_auditor
    networks:
      - beacon

  ca.co1.org:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-co1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.co1.org-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d61244f3f6461293eb45bc52599a93956d75f43495c45a0139a2f93e39716d8c_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.co1.org-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/d61244f3f6461293eb45bc52599a93956d75f43495c45a0139a2f93e39716d8c_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/co1.org/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_co1
    networks:
      - beacon

  ca.co2.org:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-co2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.co2.org-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0de2ebde2a7148a82a0d8edf35f6696d79739f8a72ee7f65f77a2b4aa05527ba_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.co2.org-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/0de2ebde2a7148a82a0d8edf35f6696d79739f8a72ee7f65f77a2b4aa05527ba_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/co2.org/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_co2
    networks:
      - beacon

  orderer.beacon.ph:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.beacon.ph
    container_name: orderer.beacon.ph
    networks:
      - beacon

  peer0.beacon.ph:
    container_name: peer0.beacon.ph
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-db1-beacon.ph:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=cdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=cdbpw
    depends_on:
      - couchdb-db1-beacon.ph
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.beacon.ph
    networks:
      - beacon
    
  peer0.co1.org:
    container_name: peer0.co1.org
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-db1-co1.org:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=cdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=cdbpw
    depends_on:
      - couchdb-db1-co1.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.co1.org
    networks:
      - beacon
  
  peer1.co1.org:
    container_name: peer1.co1.org
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-db2-co1.org:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=cdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=cdbpw
    depends_on:
      - couchdb-db2-co1.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.co1.org
    networks:
      - beacon

  peer0.co2.org:
    container_name: peer0.co2.org
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-db1-co2.org:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=cdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=cdbpw
    depends_on:
      - couchdb-db1-co2.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.co2.org
    networks:
      - beacon
  
  peer1.co2.org:
    container_name: peer1.co2.org
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-db2-co2.org:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=cdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=cdbpw
    depends_on:
      - couchdb-db2-co2.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.co2.org
    networks:
      - beacon

  peer0.auditor.ph:
    container_name: peer0.auditor.ph
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-db1-auditor.ph:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=cdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=cdbpw
    depends_on:
      - couchdb-db1-auditor.ph
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.auditor.ph
    networks:
      - beacon
  
  peer1.auditor.ph:
    container_name: peer1.auditor.ph
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-db2-auditor.ph:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=cdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=cdbpw
    depends_on:
      - couchdb-db2-auditor.ph
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.auditor.ph
    networks:
      - beacon

  couchdb-db1-beacon.ph:
    container_name: couchdb-db1-beacon.ph
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=cdb
      - COUCHDB_PASSWORD=cdbpw
    ports:
      - 5984:5984
    networks:
      - beacon

  couchdb-db1-auditor.ph:
    container_name: couchdb-db1-auditor.ph
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=cdb
      - COUCHDB_PASSWORD=cdbpw
    ports:
      - 7984:5984
    networks:
      - beacon

  couchdb-db2-auditor.ph:
    container_name: couchdb-db2-auditor.ph
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=cdb
      - COUCHDB_PASSWORD=cdbpw
    ports:
      - 8984:5984
    networks:
      - beacon

  couchdb-db1-co1.org:
    container_name: couchdb-db1-co1.org
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=cdb
      - COUCHDB_PASSWORD=cdbpw
    ports:
      - 9984:5984
    networks:
      - beacon

  couchdb-db2-co1.org:
    container_name: couchdb-db2-co1.org
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=cdb
      - COUCHDB_PASSWORD=cdbpw
    ports:
      - 10984:5984
    networks:
      - beacon

  couchdb-db1-co2.org:
    container_name: couchdb-db1-co2.org
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=cdb
      - COUCHDB_PASSWORD=cdbpw
    ports:
      - 11984:5984
    networks:
      - beacon

  couchdb-db2-co2.org:
    container_name: couchdb-db2-co2.org
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=cdb
      - COUCHDB_PASSWORD=cdbpw
    ports:
      - 13984:5984
    networks:
      - beacon

  cli-beacon:
    container_name: cli-beacon
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli-beacon
      - CORE_PEER_ADDRESS=peer0.beacon.ph:7051
      - CORE_PEER_LOCALMSPID=beaconMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/beacon.ph/peers/peer0.beacon.ph/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/beacon.ph/peers/peer0.beacon.ph/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/beacon.ph/peers/peer0.beacon.ph/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/beacon.ph/users/Admin@beacon.ph/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ../go_workspace/src/beacon-cmpgns:/opt/gopath/src/chaincode/beacon-cmpgns
        - ../go_workspace/src/beacon-transact:/opt/gopath/src/chaincode/beacon-transact
        - ../go_workspace/src/beacon-identity:/opt/gopath/src/chaincode/beacon-identity
    depends_on:
      - orderer.beacon.ph
      - peer0.beacon.ph
    networks:
      - beacon

  cli-auditor:
    container_name: cli-auditor
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli-auditor
      - CORE_PEER_ADDRESS=peer0.auditor.ph:7051
      - CORE_PEER_LOCALMSPID=auditorMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/auditor.ph/peers/peer0.auditor.ph/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/auditor.ph/peers/peer0.auditor.ph/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/auditor.ph/peers/peer0.auditor.ph/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/auditor.ph/users/Admin@auditor.ph/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ../go_workspace/src/beacon-cmpgns:/opt/gopath/src/chaincode/beacon-cmpgns
        - ../go_workspace/src/beacon-transact:/opt/gopath/src/chaincode/beacon-transact
        - ../go_workspace/src/beacon-identity:/opt/gopath/src/chaincode/beacon-identity
    depends_on:
      - orderer.beacon.ph
      - peer0.auditor.ph
    networks:
      - beacon

  cli-co1:
    container_name: cli-co1
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli-co1
      - CORE_PEER_ADDRESS=peer0.co1.org:7051
      - CORE_PEER_LOCALMSPID=co1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/co1.org/peers/peer0.co1.org/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/co1.org/peers/peer0.co1.org/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/co1.org/peers/peer0.co1.org/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/co1.org/users/Admin@co1.org/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ../go_workspace/src/beacon-cmpgns:/opt/gopath/src/chaincode/beacon-cmpgns
        - ../go_workspace/src/beacon-transact:/opt/gopath/src/chaincode/beacon-transact
        - ../go_workspace/src/beacon-identity:/opt/gopath/src/chaincode/beacon-identity
    depends_on:
      - orderer.beacon.ph
      - peer0.co1.org
    networks:
      - beacon

  cli-co2:
    container_name: cli-co2
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli-co2
      - CORE_PEER_ADDRESS=peer0.co2.org:7051
      - CORE_PEER_LOCALMSPID=co2MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/co2.org/peers/peer0.co2.org/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/co2.org/peers/peer0.co2.org/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/co2.org/peers/peer0.co2.org/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/co2.org/users/Admin@co2.org/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ../go_workspace/src/beacon-cmpgns:/opt/gopath/src/chaincode/beacon-cmpgns
        - ../go_workspace/src/beacon-transact:/opt/gopath/src/chaincode/beacon-transact
        - ../go_workspace/src/beacon-identity:/opt/gopath/src/chaincode/beacon-identity
    depends_on:
      - orderer.beacon.ph
      - peer0.co2.org
    networks:
      - beacon
