# BEACON - Based on docker-compose-e2e-template.yaml
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  beacon:
services:
  cli-donors:
    container_name: cli-donors
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli-donors
      - CORE_PEER_ADDRESS=peer0.donors.beacon.ph:7051
      - CORE_PEER_LOCALMSPID=donorsMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/donors.beacon.ph/peers/peer0.donors.beacon.ph/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/donors.beacon.ph/peers/peer0.donors.beacon.ph/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/donors.beacon.ph/peers/peer0.donors.beacon.ph/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/donors.beacon.ph/users/Admin@donors.beacon.ph/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ../go_workspace/src/beacon-co:/opt/gopath/src/chaincode/beacon-co
    networks:
      - beacon