NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.co1.org-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.co1.org-cert.pem
    OrganizationalUnitIdentifier: peer
