NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.auditor.ph-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.auditor.ph-cert.pem
    OrganizationalUnitIdentifier: peer
