# based from base/docker-compose-base.yaml
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer.beacon.ph:
    container_name: orderer.beacon.ph
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/:/var/hyperledger/orderer/
    - ../crypto-config/ordererOrganizations/beacon.ph/orderers/orderer.beacon.ph/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/beacon.ph/orderers/orderer.beacon.ph/tls/:/var/hyperledger/orderer/tls
    - orderer.beacon.ph:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.beacon.ph:
    container_name: peer0.beacon.ph
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.beacon.ph
      - CORE_PEER_ADDRESS=peer0.beacon.ph:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.beacon.ph:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.beacon.ph:7051
      - CORE_PEER_LOCALMSPID=beaconMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/beacon.ph/peers/peer0.beacon.ph/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/beacon.ph/peers/peer0.beacon.ph/tls:/etc/hyperledger/fabric/tls
        - peer0.beacon.ph:/var/hyperledger/production
        - ../go_workspace/src/beacon-cmpgns:/opt/gopath/src/chaincode/beacon-cmpgns
        - ../go_workspace/src/beacon-transact:/opt/gopath/src/chaincode/beacon-transact
        - ../go_workspace/src/beacon-identity:/opt/gopath/src/chaincode/beacon-identity
    ports:
      - 7051:7051
      - 7053:7053

  peer1.beacon.ph:
    container_name: peer1.beacon.ph
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.beacon.ph
      - CORE_PEER_ADDRESS=peer1.beacon.ph:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.beacon.ph:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.beacon.ph:7051
      - CORE_PEER_LOCALMSPID=beaconMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/beacon.ph/peers/peer1.beacon.ph/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/beacon.ph/peers/peer1.beacon.ph/tls:/etc/hyperledger/fabric/tls
        - peer1.beacon.ph:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer0.auditor.ph:
    container_name: peer0.auditor.ph
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.auditor.ph
      - CORE_PEER_ADDRESS=peer0.auditor.ph:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.auditor.ph:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.auditor.ph:7051
      - CORE_PEER_LOCALMSPID=auditorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/auditor.ph/peers/peer0.auditor.ph/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/auditor.ph/peers/peer0.auditor.ph/tls:/etc/hyperledger/fabric/tls
        - peer0.auditor.ph:/var/hyperledger/production
        - ../go_workspace/src/beacon-cmpgns:/opt/gopath/src/chaincode/beacon-cmpgns
        - ../go_workspace/src/beacon-transact:/opt/gopath/src/chaincode/beacon-transact
        - ../go_workspace/src/beacon-identity:/opt/gopath/src/chaincode/beacon-identity
    ports:
      - 8051:7051
      - 8053:7053

  peer1.auditor.ph:
    container_name: peer1.auditor.ph
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.auditor.ph
      - CORE_PEER_ADDRESS=peer1.auditor.ph:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.auditor.ph:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.auditor.ph:7051
      - CORE_PEER_LOCALMSPID=auditorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/auditor.ph/peers/peer1.auditor.ph/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/auditor.ph/peers/peer1.auditor.ph/tls:/etc/hyperledger/fabric/tls
        - peer1.auditor.ph:/var/hyperledger/production
    ports:
      - 6051:7051
      - 6053:7053

  peer0.co1.org:
    container_name: peer0.co1.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.co1.org
      - CORE_PEER_ADDRESS=peer0.co1.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.co1.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.co1.org:7051
      - CORE_PEER_LOCALMSPID=co1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/co1.org/peers/peer0.co1.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/co1.org/peers/peer0.co1.org/tls:/etc/hyperledger/fabric/tls
        - peer0.co1.org:/var/hyperledger/production
        - ../go_workspace/src/beacon-cmpgns:/opt/gopath/src/chaincode/beacon-cmpgns
        - ../go_workspace/src/beacon-transact:/opt/gopath/src/chaincode/beacon-transact
        - ../go_workspace/src/beacon-identity:/opt/gopath/src/chaincode/beacon-identity
    ports:
      - 10051:7051
      - 10053:7053

  peer1.co1.org:
    container_name: peer1.co1.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.co1.org
      - CORE_PEER_ADDRESS=peer1.co1.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.co1.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.co1.org:7051
      - CORE_PEER_LOCALMSPID=co1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/co1.org/peers/peer1.co1.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/co1.org/peers/peer1.co1.org/tls:/etc/hyperledger/fabric/tls
        - peer1.co1.org:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer0.co2.org:
    container_name: peer0.co2.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.co2.org
      - CORE_PEER_ADDRESS=peer0.co2.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.co2.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.co2.org:7051
      - CORE_PEER_LOCALMSPID=co2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/co2.org/peers/peer0.co2.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/co2.org/peers/peer0.co2.org/tls:/etc/hyperledger/fabric/tls
        - peer0.co2.org:/var/hyperledger/production
        - ../go_workspace/src/beacon-cmpgns:/opt/gopath/src/chaincode/beacon-cmpgns
        - ../go_workspace/src/beacon-transact:/opt/gopath/src/chaincode/beacon-transact
        - ../go_workspace/src/beacon-identity:/opt/gopath/src/chaincode/beacon-identity
    ports:
      - 12051:7051
      - 12053:7053

  peer1.co2.org:
    container_name: peer1.co2.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.co2.org
      - CORE_PEER_ADDRESS=peer1.co2.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.co2.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.co2.org:7051
      - CORE_PEER_LOCALMSPID=co2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/co2.org/peers/peer1.co2.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/co2.org/peers/peer1.co2.org/tls:/etc/hyperledger/fabric/tls
        - peer1.co2.org:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13053:7053