NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.donors.beacon.ph-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.donors.beacon.ph-cert.pem
    OrganizationalUnitIdentifier: peer
